### ISSUE TITLE
引入1.0.4 挂掉了

### ISSUE THREAD

**Issue by awpss** [ToDou/appbarlayout-spring-extension#23]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/math/MathUtils;
                                                                            at android.support.design.widget.AppBarLayoutSpringBehavior.setHeaderTopBottomOffset(AppBarLayoutSpringBehavior.java:288)
                                                                            at android.support.design.widget.AppBarLayoutSpringBehavior.setHeaderTopBottomOffset(AppBarLayoutSpringBehavior.java:262)
                                                                            at android.support.design.widget.AppBarLayoutSpringBehavior.setHeaderTopBottomOffset(AppBarLayoutSpringBehavior.java:19)
                                                                            at android.support.design.widget.HeaderBehavior.scroll(HeaderBehavior.java:224)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onNestedScroll(AppBarLayout.java:843)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onNestedScroll(AppBarLayout.java:758)
                                                                            at android.support.design.widget.CoordinatorLayout.onNestedScroll(CoordinatorLayout.java:1715)
                                                                            at android.support.v4.view.ViewParentCompatLollipop.onNestedScroll(ViewParentCompatLollipop.java:60)
                                                                            at android.support.v4.view.ViewParentCompat$ViewParentCompatLollipopImpl.onNestedScroll(ViewParentCompat.java:177)
                                                                            at android.support.v4.view.ViewParentCompat.onNestedScroll(ViewParentCompat.java:328)
                                                                            at android.support.v4.view.NestedScrollingChildHelper.dispatchNestedScroll(NestedScrollingChildHelper.java:163)
                                                                            at android.support.v7.widget.RecyclerView.dispatchNestedScroll(RecyclerView.java:10161)
                                                                            at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1654)
                                                                            at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2764)
                                                                            at android.view.View.dispatchTouchEvent(View.java:10012)

**Comment by ToDou** [comment]
已修复，试下1.0.5
