### ISSUE TITLE
Not support design:27.1.1 not MathUtil

### ISSUE THREAD

**Issue by ieewbbwe** [ToDou/appbarlayout-spring-extension#29]
When i use design:27.1.1 then page will crash because,
 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/design/widget/MathUtils;
                                                                       at android.support.design.widget.AppBarLayoutSpringBehavior.setHeaderTopBottomOffset(AppBarLayoutSpringBehavior.java:294)
                                                                       at android.support.design.widget.AppBarLayoutSpringBehavior.setHeaderTopBottomOffset(AppBarLayoutSpringBehavior.java:16)
                                                                       at android.support.design.widget.HeaderBehavior.scroll(HeaderBehavior.java:222)

**Comment by ToDou** [comment]
Which version did you use?

Picher.Mo <notifications@github.com> 于2018年7月23日周一 下午3:11写道：

**Comment by ieewbbwe** [comment]
I use this configs
  configs = [
            compileSdkVersion: 27,
            buildToolsVersion: '27.0.2',
            minSdkVersion    : 17,
            targetSdkVersion : 27,
            versionCode      : 1,
            versionName      : '1.0.0',
    ]
